CREATE TABLE USER (
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL UNIQUE,
  PHONE_NUMBER VARCHAR(20)
);

CREATE TABLE BOOK (
  BOOK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(128) NOT NULL,
  AUTHOR VARCHAR(128) NOT NULL,
  ISBN VARCHAR(13) NOT NULL
);

CREATE TABLE LOAN (
  LOAN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT references USER(USER_ID) NOT NULL,
  BOOK_ID BIGINT references BOOK(BOOK_ID) NOT NULL,
);